version: '3.8'
services:
  laravel:
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/var/www/html
    depends_on:
      - redis

  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app

  fastapi:
    build: ./fastapi-ms
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi-ms:/app

  redis:
    image: redis:alpine
